name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle --deployment
          gem install --no-document rspec:'~>3.1' httparty google-api-client
      - name: RSpec Report
        run: BOT_USER_OAUTH_ACCESS_TOKEN='xoxb-1504470671856-1493479172817-IA4mbwQSTSn4lVy5zAWonABt' rspec --force-color --format documentation